global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'callback-service-consumer'
    static_configs:
      - targets: ['consumer:8000']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
